version: '3.8'

services:
  web:
    build: .
    command: uvicorn main:app --host 0.0.0.0 --port 4567 --reload
    volumes:
      - .:/app
    ports:
      - "4567:8000"
    depends_on:
      - my_db
    environment:
      - DATABASE_URL=postgresql://root:test1234@my_db:5432/todo
      - POSTGRES_HOST=my_db
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=test1234
      - POSTGRES_DB=todo
      - POSTGRES_PORT=5432
    networks:
      - my-network

  my_db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=test1234
      - POSTGRES_DB=todo
    ports:
      - "5432:5432"
    networks:
      - my-network

networks:
  my-network:
    driver: bridge

volumes:
  postgres_data: